FROM node:18  

WORKDIR /usr/src/app

COPY eventswebapplication.client/package*.json ./

RUN npm install

COPY eventswebapplication.client ./

RUN npm run build

EXPOSE 51326

CMD ["npm", "run", "dev"]